theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  
title: Illia Kaliuzhnyi
description: Undergraduate mathematics student at V.N Karazin Kharkiv National University
